packages:
  - agents/*
  - packages/*

allowBuilds:
  '@alibaba-group/open-code-review': true
  core-js: true
  esbuild: true
  protobufjs: true

minimumReleaseAge: 0

onlyBuiltDependencies:
  - esbuild
  - protobufjs
