import { defineStep } from "../../runtime";
import z from "zod";
import { extractAgentConfig } from "../../../bootstrap/session";
import { type CommonRequestContext, PullRequestSchema } from "../../types";
import { type NormalizedFinding, NormalizedFindingSchema } from "../../types/finding";

// ─── Schemas ──────────────────────────────────────────────────────────────────

const CreateWorkItemsInputSchema = z.object({
  prDetails: PullRequestSchema,
  findings: z.array(NormalizedFindingSchema),
  workItemContext: z.string().optional(),
  correlationSummary: z.string(),
  changesSinceLastReview: z.string().optional(),
  reviewSummary: z.string(),
  reviewExecutionStatus: z.enum(["complete", "incomplete"]),
  reviewMetadata: z.record(z.string(), z.unknown()),
  measures: z.union([z.any(), z.null()]),
  mergeDecision: z.enum(["allowed", "blocked", "pending"]),
  auditRecordId: z.string().uuid().optional(),
});

const CreateWorkItemsOutputSchema = CreateWorkItemsInputSchema.extend({
  createdWorkItems: z.number().describe("Number of work items created"),
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Build a JSON Patch document for creating an ADO work item.
 */
function buildWorkItemPatch(
  finding: NormalizedFinding,
  prId: number,
  prUrl: string,
  _workItemType: "Bug" | "Task",
  workItemTags: string,
): Record<string, unknown>[] {
  const title = `[PR Guardian] ${finding.title} (PR #${prId})`;
  const description = [
    `## Finding Details`,
    ``,
    `**Category:** ${finding.category}`,
    `**Severity:** ${finding.severity}`,
    `**File:** ${finding.filePath ?? "N/A"}`,
    `**Lines:** ${finding.lineStart ?? ""}${finding.lineEnd ? ` - ${finding.lineEnd}` : ""}`,
    ``,
    `**Evidence:**`,
    finding.evidence,
    ``,
    `**Business Impact:**`,
    finding.businessImpact,
    ``,
    `**Remediation:**`,
    finding.remediation,
    ``,
    `---`,
    `_Generated by PR Guardian — [Pull Request #${prId}](${prUrl})_`,
  ].join("\n");

  return [
    {
      op: "add",
      path: "/fields/System.Title",
      value: title,
    },
    {
      op: "add",
      path: "/fields/System.Description",
      value: description,
    },
    {
      op: "add",
      path: "/fields/System.Tags",
      value: workItemTags,
    },
  ];
}

// ─── Step ─────────────────────────────────────────────────────────────────────

export const createWorkItems = defineStep({
  id: "create-work-items",
  description:
    "Create ADO work items for critical and high-severity findings",
  inputSchema: CreateWorkItemsInputSchema,
  outputSchema: CreateWorkItemsOutputSchema,
  execute: async ({ inputData, requestContext }) => {
    if (!inputData) {
      throw new Error("Input data not found");
    }

    const { findings, prDetails } = inputData;

    const agentConfig = extractAgentConfig(
      requestContext as unknown as CommonRequestContext,
    );

    const adoClient = agentConfig.getAdoClient();
    const rootConfig = await agentConfig.getRootConfig();

    // ── Config guard: skip if remediation task creation is not enabled ──
    if (!rootConfig.remediationTasks?.enabled) {
      return { ...inputData, createdWorkItems: 0 };
    }

    // ── Initialise FindingStore (for idempotency checks) ────────────────
    const { FindingStore } = await import("finding-store");
    const findingStore = new FindingStore();
    const findingStorePath = rootConfig.findingStorePath ?? ".ratan/data/findings.db";
    await findingStore.init(findingStorePath);

    // Build PR URL for work item description
    const org = adoClient.getOrganization();
    const project = adoClient.getProjectName();
    const repoName = encodeURIComponent(prDetails.repoName);
    const urlTemplate = rootConfig.remediationTasks?.adoUrlTemplate
      ?? "https://dev.azure.com/{org}/{project}/_git/{repo}/pullrequest/{prId}";
    const prUrl = urlTemplate
      .replace("{org}", org)
      .replace("{project}", project)
      .replace("{repo}", repoName)
      .replace("{prId}", String(prDetails.pullRequestId));
    const workItemTags = rootConfig.remediationTasks?.workItemTags ?? "PR Guardian; Code Review";

    // ── Filter to actionable findings ───────────────────────────────────
    const actionableFindings = findings.filter(
      (f) =>
        (f.severity === "critical" || f.severity === "high") &&
        f.resolution === "open",
    );

    if (actionableFindings.length === 0) {
      return { ...inputData, createdWorkItems: 0 };
    }

    // ── Get the underlying ADO WebApi for work item creation ────────────
    const webApi = adoClient.getAdoClient();
    const workItemApi = await webApi.getWorkItemTrackingApi();

    let createdCount = 0;

    for (const finding of actionableFindings) {
      // Idempotency check — skip if a work item is already linked
      const existing = findingStore.getFindingById(finding.id);
      if (existing && existing.linkedTaskId !== null) {
        // Already has a linked work item
        continue;
      }

      const workItemType = finding.severity === "critical" ? "Bug" : "Task";
      const patchDocument = buildWorkItemPatch(
        finding,
        prDetails.pullRequestId,
        prUrl,
        workItemType,
        workItemTags,
      );

      try {
        const workItem = await workItemApi.createWorkItem(
          null,
          patchDocument,
          project,
          workItemType,
        );

        const workItemId = workItem?.id;
        if (workItemId === undefined || workItemId === null) {
          console.warn(
            `[create-workitems] Created work item returned no ID for finding ${finding.id}`,
          );
          continue;
        }

        // ── Link the work item to the PR via artifact link ──────────────
        try {
          const artifactLink = {
            rel: "ArtifactLink",
            url: `vstfs:///Git/PullRequestId/${project}%2F${prDetails.repoName}%2F${prDetails.pullRequestId}`,
            attributes: {
              name: "Pull Request",
              comment: `Linked by PR Guardian for finding: ${finding.title}`,
              isLocked: false,
            },
          };
          await workItemApi.updateWorkItem(
            null,
            [
              {
                op: "add",
                path: "/relations/-",
                value: artifactLink,
              },
            ],
            workItemId,
            project,
          );
        } catch (linkErr) {
          console.warn(
            `[create-workitems] Failed to link work item ${workItemId} to PR: ${(linkErr as Error).message}`,
          );
          // Non-fatal — work item was still created
        }

        // ── Persist the linked task ID back to the finding store ─────────
        finding.linkedTaskId = workItemId;
        findingStore.upsertFinding(finding as Parameters<typeof findingStore.upsertFinding>[0]);

        createdCount++;
      } catch (err) {
        console.error(
          `[create-workitems] Failed to create work item for finding ${finding.id}: ${(err as Error).message}`,
        );
        // Continue with the next finding
      }
    }

    return { ...inputData, createdWorkItems: createdCount };
  },
});
