import type {
  JsonPatchOperation,
  Operation,
} from "azure-devops-node-api/interfaces/common/VSSInterfaces";
import { html2markdown, jsonToMarkdown, p } from "ratan-markdown-tool";

const AGENT_VERSION = "v0.9";
export const botWrap = (comment: string) => {
  return (
    comment +
    jsonToMarkdown([
      p("---"),
      p(
        `🤖 *This comment was generated by **Ratan Code Review Agent** ${AGENT_VERSION}. AI can make mistakes, so double-check it*`,
      ),
    ])
  );
};

export const getEmptyUser = () => ({
  displayName: "",
  uniqueName: "",
  id: "",
  url: "",
  imageUrl: "",
  descriptor: "",
});

export const extractIdFromEmail = (email: string): string => {
  const [id, _domain] = email.split("@");
  return id;
};

export const plainWorkItemPayload2JsonPatchDocument = (
  payload: Record<string, string>,
  op: Operation,
): JsonPatchOperation[] => {
  const patchDocument: JsonPatchOperation[] = [];

  for (const [key, value] of Object.entries(payload)) {
    patchDocument.push({
      op,
      path: key,
      value,
    });
  }

  return patchDocument;
};

export const objectWorkItemPayload2JsonPatchDocument = (
  path: string,
  payload: { rel: string; url: string; attributes?: { [key: string]: any } }[],
  op: Operation,
): JsonPatchOperation[] => {
  const patchDocument: JsonPatchOperation[] = [];

  for (const { rel, url, attributes } of payload) {
    const value = { rel, url, attributes };
    patchDocument.push({
      op,
      path,
      value,
    });
  }

  return patchDocument;
};

export const parseDeploymentComponents = (text: string): string[] => {
  return (
    String(html2markdown(text))
      .split("\n")
      .map((i) => i.trim())
      .map((i) => i.replace(/\\_/g, "_"))
      .filter(Boolean) || []
  );
};

export const splitDeploymentComponents = (text: string): string[] => {
  return (
    text
      .split("_")
      .map((i) => i.trim())
      .filter(Boolean) || []
  );
};

// parse 51358-mfe-cashflow-blotter-node-ansible-released-https://dev.azure.com/sc-ado/FMQPR/_build/results?buildId=6908962
// to ["51358-mfe-cashflow-blotter", 6908962]
export const parsePipelineRunFromReleaseDoc = (
  run: string,
  deploymentComponents: string[],
): {
  repo: string;
  command: string;
  buildId: number;
  buildUrl: string;
} => {
  const index = run.lastIndexOf("https://dev.azure.com/");
  if (index === -1) {
    return { repo: run, command: "", buildId: 0, buildUrl: "" };
  }
  const buildUrl = run.substring(index);
  const buildIdMatch = buildUrl?.match(/buildId=(\d+)/);
  const buildId = buildIdMatch ? Number.parseInt(buildIdMatch[1], 10) : 0;
  const repoPart = run.substring(0, index - 1);

  const deploymentComponentsStartedList = deploymentComponents.filter((dc) =>
    repoPart.startsWith(dc),
  );

  const deploymentComponentsStarted = deploymentComponentsStartedList
    .sort((a, b) => b.length - a.length)
    .at(0);

  if (deploymentComponentsStarted) {
    const [repo, ...rest] = splitDeploymentComponents(
      deploymentComponentsStarted,
    );

    return { repo, command: rest.join("_"), buildId, buildUrl };
  }

  return { repo: repoPart, command: "", buildId, buildUrl };
};

// get the first link from the HTML string
export const getLinkFromHtml = (html: string): string => {
  const linkMatch = html.match(/<a href="([^"]+)">/);
  return linkMatch ? linkMatch[1] : "";
};

// refs/heads/xxx => xxx
export const extractBranchFromSourceBranch = (sourceBranch: string) => {
  return sourceBranch.replace(/^refs\/heads\//, "");
};

// https://dev.azure.com/sc-ado/777f0ba6-cfdf-4f44-99dd-ae1dc434f5c5/_apis/wit/workItems/8867613
export const extractWorkitemIdFromUrl = (url: string): number => {
  const match = url.match(/\/workItems\/(\d+)/);
  return match ? Number.parseInt(match[1], 10) : 0;
};

export const dateToDateString = (date: string | Date): string => {
  if (typeof date === "string") {
    return date;
  } else if (date instanceof Date) {
    return date.toISOString(); // Convert Date to YYYY-MM-DD format
  }
  return "";
};

export const workitemMarkdownWrap = (workitemId: string | number) => {
  return `[${workitemId.toString()}](https://dev.azure.com/sc-ado/FMQPR/_workitems/edit/${workitemId})`;
};

const fieldsShouldSplit = [
  "Custom.Testingtypeinscope",
  "System.Tags",
  "Custom.ApplicableSecurityControls",
];
export const parseReleaseWorkitemCustomAndSystemFields = (
  workItemFields: Record<string, any>,
) => {
  return Object.keys(workItemFields).reduce(
    (acc, key) => {
      if (key.startsWith("Custom.") || key.startsWith("System.")) {
        const newKey = key.slice(7);
        const formattedKey = UpperCamelToLowerCamel(newKey); //newKey.charAt(0).toLowerCase() + newKey.slice(1);
        if (fieldsShouldSplit.includes(key)) {
          acc[formattedKey] = (workItemFields[key] ?? "")
            .split(";")
            .map((i: string) => i.trim())
            .filter(Boolean);
        } else if (workItemFields[key]?.displayName) {
          acc[formattedKey] = {
            userId: extractIdFromEmail(workItemFields[key]?.uniqueName),
            displayName: workItemFields[key]?.displayName,
            uniqueName: workItemFields[key]?.uniqueName,
          };
        } else {
          acc[formattedKey] = workItemFields[key] ?? "";
        }
      }
      return acc;
    },
    {} as Record<string, any>,
  );
};

/**
 * Converts a string from UpperCamelCase to lowerCamelCase.
 * @example
 *
 * const result = UpperCamelToLowerCamel("UPPERCamelCase");
 * console.log(result); // Output: "upperCamelCase"
 *
 * @param str The string to convert.
 * @returns The converted lowerCamelCase string.
 */
const UpperCamelToLowerCamel = (str: string) => {
  if (!str) {
    return "";
  }
  let i = 0;
  while (
    i < str.length &&
    str[i] === str[i].toUpperCase() &&
    /[A-Z]/.test(str[i])
  ) {
    i++;
  }
  if (i === 0) {
    return str;
  }
  if (i === 1) {
    return str[0].toLowerCase() + str.slice(1);
  }
  // More than one leading uppercase letter: lower all but the last
  return str.slice(0, i - 1).toLowerCase() + str[i - 1] + str.slice(i);
};
